name: cas_house
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  cupertino_icons: ^1.0.6
  auto_size_text: ^3.0.0
  material_design_icons_flutter: ^7.0.7296
  provider: ^6.1.2
  flutter_spinkit: ^5.1.0
  currency_picker: ^2.0.7
  flutter_bloc: ^8.0.0
  equatable: ^2.0.0
  build_runner: ^2.4.5
  text_scroll: ^0.2.0
  image_picker: ^1.0.4
  path_provider: ^2.1.2
  intl: ^0.18.1
  url_launcher: ^6.2.5
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.0.15
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0
  marquee: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
